language: ruby
install:
  - gem install bundler
  - bundle
rvm:
  - ruby-head
  - 2.2.2
  - 2.1.6
  - 2.0.0
script:
  - bundle exec ruby test/example.rb
notifications:
  email:
    recipients:
      - whosekiteneverfly@gmail.com
    on_success: never
    on_failure: never
matrix:
  allow_failures:
    - rvm: ruby-head
